import Head from "next/head";
import Navbar from "@/component/navbar";
import styles from "@/styles/Home.module.css"
import blogsData from "@/blog data/blog.json"
import Link from "next/link";
const Home  =({blog})=>{
 

  return(
   <>
    <Head>
       <title>Coding Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className={styles.main}>
        <h1>Personal Blogs</h1>
        <h3>connnecting developers ,unleashing ideas</h3>
        <img src="./blog.jpg" alt="" height={300} width={300} />
      </div>

      <div className={styles.contentdiv}>
        <h3>Popular blogs</h3>

       <p>
    
<ul className={styles.blog}>

{blog.map((eachblog) => {
          return(
            <div className={styles.bloglist} >
            <li key={eachblog.id} >
            <h2 >{eachblog.title}</h2>
            <p >{eachblog.content.slice(0,400)}</p>
           <Link href='/blog'> <button>Read more..</button></Link>
          </li>
          </div>
          )
        }
          
        )}
</ul>
       </p>
      </div>
   </>
  )
}


export async function getStaticProps(){
return{
  props : {
    blog : blogsData
  }
}
}

export default Home;